### ISSUE TITLE
Add Super Formula SF23

### ISSUE THREAD

**Issue by samkatakouzinosracing** [samkatakouzinosracing/nspace.hu-soundshift#111]
superformulasf23 toyota  
Super Formula SF23 - Toyota  

|Key|Value|  
|-|-|  
|DriverCarGearNeutral	|	1|  
|DriverCarGearNumForward	|	6|  
|DriverCarGearReverse	|	1|  
|DriverCarIdleRPM	|	2800|  
|DriverCarIdx	|	13|  
|DriverCarIsElectric	|	0|  
|DriverCarMaxFuelPct	|	1|  
|DriverCarRedLine	|	9325|  
|DriverCarSLBlinkRPM	|	9100|  
|DriverCarSLFirstRPM	|	7300|  
|DriverCarSLLastRPM	|	8700|  
|DriverCarSLShiftRPM	|	7900|

**Comment by HawaiiLife745** [comment]
iRacing Manual states the ideal shift point is at 9300 RPM
