### ISSUE TITLE
Edit Lamborghini Huracán GT3 EVO shift point to 8000 rpm

### ISSUE THREAD

**Issue by SoOlditHurts** [samkatakouzinosracing/nspace.hu-soundshift#61]
According to the Lamborgini Huracán GT3 EVO! User Manual from iRacing, the shift point is at 8000. The current ini file has it as 7200.

"Upshifting is recommended when the shift lights on the dashboard are fully illuminated in blue. This is at approximately 8000 rpm."

**Comment by samkatakouzinosracing** [comment]
Thank you for bringing this to attention. 
I tested the car and your point is valid. 
I've made the pull request #69 to resolve this issue.
