### ISSUE TITLE
Add Mercedes-AMG GT3 2020

### ISSUE THREAD

**Issue by samkatakouzinosracing** [samkatakouzinosracing/nspace.hu-soundshift#80]
| Key                     | Value |
|-------------------------|-------|
| DriverCarGearNeutral    | 1     |
| DriverCarGearNumForward | 6     |
| DriverCarGearReverse    | 1     |
| DriverCarIdleRPM        | 1447  |
| DriverCarRedLine        | 7505  |
| DriverCarSLBlinkRPM     | 7777  |
| DriverCarSLFirstRPM     | 6600  |
| DriverCarSLLastRPM      | 7320  |
| DriverCarSLShiftRPM     | 7200  |

^ Credits: @Fuzzwah [link](https://github.com/samkatakouzinosracing/nspace.hu-soundshift/issues/80#issuecomment-1150491692)

**Comment by Fuzzwah** [comment]
| Key                     | Value |
|-------------------------|-------|
| DriverCarGearNeutral    | 1     |
| DriverCarGearNumForward | 6     |
| DriverCarGearReverse    | 1     |
| DriverCarIdleRPM        | 1447  |
| DriverCarRedLine        | 7505  |
| DriverCarSLBlinkRPM     | 7777  |
| DriverCarSLFirstRPM     | 6600  |
| DriverCarSLLastRPM      | 7320  |
| DriverCarSLShiftRPM     | 7200  |
